[build]
  # Carpeta donde est치 el c칩digo de la aplicaci칩n
  base = "app"
  # Carpeta que se genera tras el build y que Netlify debe servir
  publish = "dist"
  # Comando para compilar
  command = "npm run build"

[[redirects]]
  # Esto soluciona el error 404 al refrescar p치ginas en una React SPA
  from = "/*"
  to = "/index.html"
  status = 200
